version: 0.2

environment_variables:
  plaintext:
    BUCKET_NAME: "open-security-summit.com-cdn"

phases:
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR && git clone https://github.com/devcows/hugo-universal-theme.git themes/oss-owasp
  build:
    commands:
      - hugo -v
  post_build:
    commands:
      - minify -r -o public/ public/
      - s3deploy -source=public/ -region=eu-west-2 -bucket=${BUCKET_NAME}
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id E22WEBPD6529KA --paths '/*'
