version: 0.2

environment_variables:
  plaintext:
    HUGO_VERSION: "0.40.1"
    STOUT_VERSION: "1.3.1"
    BUCKET_NAME: "open-security-summit.com-cdn"

phases:
  install:
    commands:
      # Install hugo 
      - curl -Ls https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - tar xf /tmp/hugo.tar.gz -C /usr/local/bin
      - go get -u -v github.com/bep/s3deploy
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR && git clone https://github.com/devcows/hugo-universal-theme.git themes/oss-owasp
  build:
    commands:
      - hugo -v
  post_build:
    commands:
      - s3deploy -source=public/ -region=eu-west-1 -bucket=${BUCKET_NAME}
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id E22WEBPD6529KA --paths '/*'
