version: 0.1
phases:
  #install:
  #  commands:
      # Install hugo 
  #    - go get -v github.com/gohugoio/hugo
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws s3 sync --delete public/ "s3://${BUCKET_NAME}"
